### ISSUE TITLE
Standard.at erkennt mittlerweile Cookie-Manipulation

### ISSUE THREAD

**Issue by flograd** [moxus/derstandard-fairuse#1]
Leider funktioniert die Erweiterung nicht mehr. Anmelden auf derstandard.at mit aktiver Erweiterung führt zu der Meldung:
"Liebe/r User/in, aufgrund einer Cookie-Manipulation ist derzeit leider kein Login möglich. Bitte deinstallieren sie Browser-Plugins, die Cookies manipulieren und versuchen Sie es erneut."

**Comment by moxus** [comment]
Die Neue Version 1.1 sollte das Problem beheben. Für Testfeedback bin ich dankbar :)

**Comment by flograd** [comment]
Schaut sehr gut aus. Konnte mich mit der neuen Version ohne Probleme anmelden und trotz aktiviertem Adblocker gibts keine Fair-Use-Störungen. 
Werde es noch weiter verfolgen, aber sieht wirklich gut aus. 

Ach und super-schnell reagiert ;)

**Comment by flograd** [comment]
Etwas zu früh gefreut. Das Anmelden funktioniert einwandfrei für die ersten Minuten und es werden auch alle Fair-Use-Einschränkungen ausgeblendet trotz aktiviertem Adblocker. Nach einigen Minuten allerdings ist die Funktion der Erweiterung dahin und plötzlich tauchen die Fair-Use-Einschränkungen auf. 
Da scheint der sanftere Umgang mit den Cookies die Funktion auszuhebeln. :/
